### ISSUE TITLE
[Android Bootcamp] Group Project - Travel Journal: Sprint 1 - Ready for Review

### ISSUE THREAD

**Issue by esrako** [TeamTravelJournal/AndroidTravelJournalApp#44]
Our gif walkthrough for Sprint 1 is ready and can be seen in readme.
Thanks.

/cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work creating wire-frames and distributing stories/tasks for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:
- It is important create tasks for each of your stories/features and have them assigned to team members in the form of issues. Please take care of this before you work on sprint 2.
- Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you group all issues into milestones representing sprints so that its easier for you to track progress of the project.
- Consider creating group [milestones/pull requests](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) to better track your progress and review each others code.
- Good job by everyone to contribute to the project.
- Consider creating tasks to complete the creation of your database schema and its respective models. Also, consider integrating with Parse if you haven't already.
- Good to see that your team created regular pull requests to sync up your code to avoid having multiple conflicts at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on.  It is those little extra things you do that make everything feel more polished and desirable to use.
